using System;
using SLua;
using System.Collections.Generic;
[UnityEngine.Scripting.Preserve]
public class Lua_GameFrameworkMessage_LobbyMessageDefine : LuaObject {
	static public void reg(IntPtr l) {
		getEnumTable(l,"GameFrameworkMessage.LobbyMessageDefine");
		addMember(l,1,"NodeRegister");
		addMember(l,2,"NodeRegisterResult");
		addMember(l,3,"VersionVerify");
		addMember(l,4,"VersionVerifyResult");
		addMember(l,5,"DirectLogin");
		addMember(l,6,"AccountLogout");
		addMember(l,7,"Logout");
		addMember(l,8,"GetQueueingCount");
		addMember(l,9,"UserHeartbeat");
		addMember(l,10,"KickUser");
		addMember(l,11,"TooManyOperations");
		addMember(l,12,"RequestNickname");
		addMember(l,13,"RequestSceneRoomInfo");
		addMember(l,14,"RequestSceneRoomList");
		addMember(l,15,"ServerShutdown");
		addMember(l,16,"Msg_CL_GetMailList");
		addMember(l,17,"Msg_LC_NotifyNewMail");
		addMember(l,18,"GmCode");
		addMember(l,19,"AccountLogin");
		addMember(l,20,"AccountLoginResult");
		addMember(l,21,"QueueingCountResult");
		addMember(l,22,"RequestNicknameResult");
		addMember(l,23,"ChangeName");
		addMember(l,24,"ChangeNameResult");
		addMember(l,25,"RoleEnter");
		addMember(l,26,"FriendInfoForMessage");
		addMember(l,27,"MemberInfoForMessage");
		addMember(l,28,"ItemInfoForMessage");
		addMember(l,29,"RoleEnterResult");
		addMember(l,30,"EnterScene");
		addMember(l,31,"ChangeSceneRoom");
		addMember(l,32,"EnterSceneResult");
		addMember(l,33,"QuitRoom");
		addMember(l,34,"MailItemForMessage");
		addMember(l,35,"MailInfoForMessage");
		addMember(l,36,"Msg_LC_SyncMailList");
		addMember(l,37,"Msg_CL_ReadMail");
		addMember(l,38,"Msg_CL_ReceiveMail");
		addMember(l,39,"Msg_CL_DeleteMail");
		addMember(l,40,"Msg_LC_LackOfSpace");
		addMember(l,41,"Msg_LC_SyncFriendList");
		addMember(l,42,"Msg_CL_AddFriend");
		addMember(l,43,"Msg_LC_AddFriend");
		addMember(l,44,"Msg_CL_RemoveFriend");
		addMember(l,45,"Msg_LC_RemoveFriend");
		addMember(l,46,"Msg_CL_MarkBlack");
		addMember(l,47,"Msg_LC_MarkBlack");
		addMember(l,48,"Msg_LC_SyncRoleInfo");
		addMember(l,49,"Msg_LC_SyncMemberList");
		addMember(l,50,"Msg_LC_SyncItemList");
		addMember(l,51,"Msg_CL_UseItem");
		addMember(l,52,"Msg_CL_DiscardItem");
		addMember(l,53,"Msg_CLC_StoryMessage");
		addMember(l,54,"Msg_LC_PublishEvent");
		addMember(l,55,"Msg_LC_SendGfxMessage");
		addMember(l,56,"Msg_LC_HighlightPrompt");
		addMember(l,57,"MaxNum");
		LuaDLL.lua_pop(l, 1);
	}
}
