//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoFiles/BigworldAndRoomServer.proto
namespace GameFrameworkMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_BL_BroadcastText")]
  public partial class Msg_BL_BroadcastText : global::ProtoBuf.IExtensible
  {
    public Msg_BL_BroadcastText() {}
    
    private int _BroadcastType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"BroadcastType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int BroadcastType
    {
      get { return _BroadcastType; }
      set { _BroadcastType = value; }
    }
    private string _Content;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private int _RollCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"RollCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RollCount
    {
      get { return _RollCount; }
      set { _RollCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_BL_QueryUserStateResult")]
  public partial class Msg_BL_QueryUserStateResult : global::ProtoBuf.IExtensible
  {
    public Msg_BL_QueryUserStateResult() {}
    
    private ulong _Guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Guid
    {
      get { return _Guid; }
      set { _Guid = value; }
    }
    private int _State;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"State", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int State
    {
      get { return _State; }
      set { _State = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_BL_UserOffline")]
  public partial class Msg_BL_UserOffline : global::ProtoBuf.IExtensible
  {
    public Msg_BL_UserOffline() {}
    
    private ulong _Guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Guid
    {
      get { return _Guid; }
      set { _Guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LB_BigworldUserBaseInfo")]
  public partial class Msg_LB_BigworldUserBaseInfo : global::ProtoBuf.IExtensible
  {
    public Msg_LB_BigworldUserBaseInfo() {}
    
    private string _NodeName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"NodeName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string NodeName
    {
      get { return _NodeName; }
      set { _NodeName = value; }
    }
    private int _WorldId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"WorldId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int WorldId
    {
      get { return _WorldId; }
      set { _WorldId = value; }
    }
    private string _AccountId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"AccountId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AccountId
    {
      get { return _AccountId; }
      set { _AccountId = value; }
    }
    private string _ClientInfo;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ClientInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ClientInfo
    {
      get { return _ClientInfo; }
      set { _ClientInfo = value; }
    }
    private string _StartServerTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"StartServerTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string StartServerTime
    {
      get { return _StartServerTime; }
      set { _StartServerTime = value; }
    }
    private int _FightingCapacity;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"FightingCapacity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int FightingCapacity
    {
      get { return _FightingCapacity; }
      set { _FightingCapacity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LB_CancelMatch")]
  public partial class Msg_LB_CancelMatch : global::ProtoBuf.IExtensible
  {
    public Msg_LB_CancelMatch() {}
    
    private ulong _Guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Guid
    {
      get { return _Guid; }
      set { _Guid = value; }
    }
    private int _Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LB_QueryUserState")]
  public partial class Msg_LB_QueryUserState : global::ProtoBuf.IExtensible
  {
    public Msg_LB_QueryUserState() {}
    
    private ulong _Guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Guid
    {
      get { return _Guid; }
      set { _Guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LB_RequestEnterScene")]
  public partial class Msg_LB_RequestEnterScene : global::ProtoBuf.IExtensible
  {
    public Msg_LB_RequestEnterScene() {}
    
    private GameFrameworkMessage.Msg_LB_BigworldUserBaseInfo _BaseInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"BaseInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public GameFrameworkMessage.Msg_LB_BigworldUserBaseInfo BaseInfo
    {
      get { return _BaseInfo; }
      set { _BaseInfo = value; }
    }
    private GameFrameworkMessage.Msg_LR_RoomUserInfo _User;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"User", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public GameFrameworkMessage.Msg_LR_RoomUserInfo User
    {
      get { return _User; }
      set { _User = value; }
    }
    private int _SceneId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SceneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SceneId
    {
      get { return _SceneId; }
      set { _SceneId = value; }
    }
    private int _WantRoomId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"WantRoomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int WantRoomId
    {
      get { return _WantRoomId; }
      set { _WantRoomId = value; }
    }
    private int _FromSceneId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"FromSceneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int FromSceneId
    {
      get { return _FromSceneId; }
      set { _FromSceneId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LB_UpdateUserServerInfo")]
  public partial class Msg_LB_UpdateUserServerInfo : global::ProtoBuf.IExtensible
  {
    public Msg_LB_UpdateUserServerInfo() {}
    
    private int _WorldId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"WorldId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int WorldId
    {
      get { return _WorldId; }
      set { _WorldId = value; }
    }
    private int _UserCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"UserCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int UserCount
    {
      get { return _UserCount; }
      set { _UserCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LB_UserOffline")]
  public partial class Msg_LB_UserOffline : global::ProtoBuf.IExtensible
  {
    public Msg_LB_UserOffline() {}
    
    private ulong _Guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Guid
    {
      get { return _Guid; }
      set { _Guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LB_UserRelogin")]
  public partial class Msg_LB_UserRelogin : global::ProtoBuf.IExtensible
  {
    public Msg_LB_UserRelogin() {}
    
    private ulong _Guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Guid
    {
      get { return _Guid; }
      set { _Guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LBL_Message")]
  public partial class Msg_LBL_Message : global::ProtoBuf.IExtensible
  {
    public Msg_LBL_Message() {}
    
    private GameFrameworkMessage.Msg_LBL_Message.MsgTypeEnum _MsgType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MsgType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.Msg_LBL_Message.MsgTypeEnum MsgType
    {
      get { return _MsgType; }
      set { _MsgType = value; }
    }
    private string _TargetName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"TargetName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TargetName
    {
      get { return _TargetName; }
      set { _TargetName = value; }
    }
    private byte[] _Data;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MsgTypeEnum")]
    public enum MsgTypeEnum
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Node", Value=0)]
      Node = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Room", Value=1)]
      Room = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LR_ActiveScene")]
  public partial class Msg_LR_ActiveScene : global::ProtoBuf.IExtensible
  {
    public Msg_LR_ActiveScene() {}
    
    private ulong _UserGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserGuid
    {
      get { return _UserGuid; }
      set { _UserGuid = value; }
    }
    private int _RoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RoomID
    {
      get { return _RoomID; }
      set { _RoomID = value; }
    }
    private int _SceneId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SceneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SceneId
    {
      get { return _SceneId; }
      set { _SceneId = value; }
    }
    private readonly global::System.Collections.Generic.List<GameFrameworkMessage.Msg_LR_RoomUserInfo> _UserInfos = new global::System.Collections.Generic.List<GameFrameworkMessage.Msg_LR_RoomUserInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"UserInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameFrameworkMessage.Msg_LR_RoomUserInfo> UserInfos
    {
      get { return _UserInfos; }
    }
  
    private int _HPs = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"HPs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HPs
    {
      get { return _HPs; }
      set { _HPs = value; }
    }
    private int _MPs = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"MPs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MPs
    {
      get { return _MPs; }
      set { _MPs = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LR_ChangeScene")]
  public partial class Msg_LR_ChangeScene : global::ProtoBuf.IExtensible
  {
    public Msg_LR_ChangeScene() {}
    
    private ulong _UserGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserGuid
    {
      get { return _UserGuid; }
      set { _UserGuid = value; }
    }
    private int _RoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RoomID
    {
      get { return _RoomID; }
      set { _RoomID = value; }
    }
    private int _TargetRoomID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"TargetRoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int TargetRoomID
    {
      get { return _TargetRoomID; }
      set { _TargetRoomID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LR_EnterScene")]
  public partial class Msg_LR_EnterScene : global::ProtoBuf.IExtensible
  {
    public Msg_LR_EnterScene() {}
    
    private ulong _UserGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserGuid
    {
      get { return _UserGuid; }
      set { _UserGuid = value; }
    }
    private int _RoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RoomID
    {
      get { return _RoomID; }
      set { _RoomID = value; }
    }
    private GameFrameworkMessage.Msg_LR_RoomUserInfo _UserInfo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"UserInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public GameFrameworkMessage.Msg_LR_RoomUserInfo UserInfo
    {
      get { return _UserInfo; }
      set { _UserInfo = value; }
    }
    private int _HP = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"HP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HP
    {
      get { return _HP; }
      set { _HP = value; }
    }
    private int _MP = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"MP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MP
    {
      get { return _MP; }
      set { _MP = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LR_ReclaimItem")]
  public partial class Msg_LR_ReclaimItem : global::ProtoBuf.IExtensible
  {
    public Msg_LR_ReclaimItem() {}
    
    private ulong _UserGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserGuid
    {
      get { return _UserGuid; }
      set { _UserGuid = value; }
    }
    private int _RoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RoomID
    {
      get { return _RoomID; }
      set { _RoomID = value; }
    }
    private int _ItemId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ItemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ItemId
    {
      get { return _ItemId; }
      set { _ItemId = value; }
    }
    private string _Model;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Model", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Model
    {
      get { return _Model; }
      set { _Model = value; }
    }
    private string _Particle;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Particle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Particle
    {
      get { return _Particle; }
      set { _Particle = value; }
    }
    private int _TipDict;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"TipDict", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int TipDict
    {
      get { return _TipDict; }
      set { _TipDict = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LR_ReconnectUser")]
  public partial class Msg_LR_ReconnectUser : global::ProtoBuf.IExtensible
  {
    public Msg_LR_ReconnectUser() {}
    
    private ulong _UserGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserGuid
    {
      get { return _UserGuid; }
      set { _UserGuid = value; }
    }
    private int _RoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RoomID
    {
      get { return _RoomID; }
      set { _RoomID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LR_ReplyRegisterRoomServer")]
  public partial class Msg_LR_ReplyRegisterRoomServer : global::ProtoBuf.IExtensible
  {
    public Msg_LR_ReplyRegisterRoomServer() {}
    
    private bool _IsOk;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"IsOk", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsOk
    {
      get { return _IsOk; }
      set { _IsOk = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LR_RoomUserInfo")]
  public partial class Msg_LR_RoomUserInfo : global::ProtoBuf.IExtensible
  {
    public Msg_LR_RoomUserInfo() {}
    
    private ulong _Guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Guid
    {
      get { return _Guid; }
      set { _Guid = value; }
    }
    private string _Nick;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Nick
    {
      get { return _Nick; }
      set { _Nick = value; }
    }
    private uint _Key;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Key
    {
      get { return _Key; }
      set { _Key = value; }
    }
    private int _Hero;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Hero", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Hero
    {
      get { return _Hero; }
      set { _Hero = value; }
    }
    private int _Camp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Camp
    {
      get { return _Camp; }
      set { _Camp = value; }
    }
    private bool _IsMachine;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"IsMachine", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsMachine
    {
      get { return _IsMachine; }
      set { _IsMachine = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private float _EnterX = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"EnterX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float EnterX
    {
      get { return _EnterX; }
      set { _EnterX = value; }
    }
    private float _EnterY = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"EnterY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float EnterY
    {
      get { return _EnterY; }
      set { _EnterY = value; }
    }
    private readonly global::System.Collections.Generic.List<GameFrameworkMessage.Msg_LR_RoomUserInfo.MemberInfo> _Members = new global::System.Collections.Generic.List<GameFrameworkMessage.Msg_LR_RoomUserInfo.MemberInfo>();
    [global::ProtoBuf.ProtoMember(10, Name=@"Members", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameFrameworkMessage.Msg_LR_RoomUserInfo.MemberInfo> Members
    {
      get { return _Members; }
    }
  
    private int _SummonerSkillId;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"SummonerSkillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SummonerSkillId
    {
      get { return _SummonerSkillId; }
      set { _SummonerSkillId = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MemberInfo")]
  public partial class MemberInfo : global::ProtoBuf.IExtensible
  {
    public MemberInfo() {}
    
    private int _Hero;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Hero", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Hero
    {
      get { return _Hero; }
      set { _Hero = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LR_UserQuit")]
  public partial class Msg_LR_UserQuit : global::ProtoBuf.IExtensible
  {
    public Msg_LR_UserQuit() {}
    
    private ulong _UserGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserGuid
    {
      get { return _UserGuid; }
      set { _UserGuid = value; }
    }
    private int _RoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RoomID
    {
      get { return _RoomID; }
      set { _RoomID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LR_UserReLive")]
  public partial class Msg_LR_UserReLive : global::ProtoBuf.IExtensible
  {
    public Msg_LR_UserReLive() {}
    
    private ulong _UserGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserGuid
    {
      get { return _UserGuid; }
      set { _UserGuid = value; }
    }
    private int _RoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RoomID
    {
      get { return _RoomID; }
      set { _RoomID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LRL_StoryMessage")]
  public partial class Msg_LRL_StoryMessage : global::ProtoBuf.IExtensible
  {
    public Msg_LRL_StoryMessage() {}
    
    private int _RoomId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RoomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RoomId
    {
      get { return _RoomId; }
      set { _RoomId = value; }
    }
    private ulong _UserGuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"UserGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserGuid
    {
      get { return _UserGuid; }
      set { _UserGuid = value; }
    }
    private string _MsgId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"MsgId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string MsgId
    {
      get { return _MsgId; }
      set { _MsgId = value; }
    }
    private readonly global::System.Collections.Generic.List<GameFrameworkMessage.Msg_LRL_StoryMessage.MessageArg> _Args = new global::System.Collections.Generic.List<GameFrameworkMessage.Msg_LRL_StoryMessage.MessageArg>();
    [global::ProtoBuf.ProtoMember(4, Name=@"Args", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameFrameworkMessage.Msg_LRL_StoryMessage.MessageArg> Args
    {
      get { return _Args; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageArg")]
  public partial class MessageArg : global::ProtoBuf.IExtensible
  {
    public MessageArg() {}
    
    private GameFrameworkMessage.Msg_LRL_StoryMessage.ArgType _val_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"val_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.Msg_LRL_StoryMessage.ArgType val_type
    {
      get { return _val_type; }
      set { _val_type = value; }
    }
    private string _str_val;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"str_val", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string str_val
    {
      get { return _str_val; }
      set { _str_val = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ArgType")]
    public enum ArgType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NULL", Value=0)]
      NULL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INT", Value=1)]
      INT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FLOAT", Value=2)]
      FLOAT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STRING", Value=3)]
      STRING = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RL_ActiveSceneResult")]
  public partial class Msg_RL_ActiveSceneResult : global::ProtoBuf.IExtensible
  {
    public Msg_RL_ActiveSceneResult() {}
    
    private readonly global::System.Collections.Generic.List<ulong> _UserGuids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(1, Name=@"UserGuids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> UserGuids
    {
      get { return _UserGuids; }
    }
  
    private int _RoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RoomID
    {
      get { return _RoomID; }
      set { _RoomID = value; }
    }
    private int _Result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RL_ChangeScene")]
  public partial class Msg_RL_ChangeScene : global::ProtoBuf.IExtensible
  {
    public Msg_RL_ChangeScene() {}
    
    private ulong _UserGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserGuid
    {
      get { return _UserGuid; }
      set { _UserGuid = value; }
    }
    private int _SceneID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SceneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SceneID
    {
      get { return _SceneID; }
      set { _SceneID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RL_ChangeSceneResult")]
  public partial class Msg_RL_ChangeSceneResult : global::ProtoBuf.IExtensible
  {
    public Msg_RL_ChangeSceneResult() {}
    
    private ulong _UserGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserGuid
    {
      get { return _UserGuid; }
      set { _UserGuid = value; }
    }
    private int _RoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RoomID
    {
      get { return _RoomID; }
      set { _RoomID = value; }
    }
    private int _TargetRoomID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"TargetRoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int TargetRoomID
    {
      get { return _TargetRoomID; }
      set { _TargetRoomID = value; }
    }
    private int _Result;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private int _HP = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"HP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HP
    {
      get { return _HP; }
      set { _HP = value; }
    }
    private int _MP = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"MP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MP
    {
      get { return _MP; }
      set { _MP = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RL_EnterSceneResult")]
  public partial class Msg_RL_EnterSceneResult : global::ProtoBuf.IExtensible
  {
    public Msg_RL_EnterSceneResult() {}
    
    private ulong _UserGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserGuid
    {
      get { return _UserGuid; }
      set { _UserGuid = value; }
    }
    private int _RoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RoomID
    {
      get { return _RoomID; }
      set { _RoomID = value; }
    }
    private int _Result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RL_PickItem")]
  public partial class Msg_RL_PickItem : global::ProtoBuf.IExtensible
  {
    public Msg_RL_PickItem() {}
    
    private ulong _UserGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserGuid
    {
      get { return _UserGuid; }
      set { _UserGuid = value; }
    }
    private int _RoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RoomID
    {
      get { return _RoomID; }
      set { _RoomID = value; }
    }
    private int _ItemId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ItemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ItemId
    {
      get { return _ItemId; }
      set { _ItemId = value; }
    }
    private string _Model;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Model", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Model
    {
      get { return _Model; }
      set { _Model = value; }
    }
    private string _Particle;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Particle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Particle
    {
      get { return _Particle; }
      set { _Particle = value; }
    }
    private string _RoomSvrName = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"RoomSvrName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string RoomSvrName
    {
      get { return _RoomSvrName; }
      set { _RoomSvrName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RL_PickMoney")]
  public partial class Msg_RL_PickMoney : global::ProtoBuf.IExtensible
  {
    public Msg_RL_PickMoney() {}
    
    private ulong _UserGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserGuid
    {
      get { return _UserGuid; }
      set { _UserGuid = value; }
    }
    private int _Num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Num
    {
      get { return _Num; }
      set { _Num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RL_RegisterRoomServer")]
  public partial class Msg_RL_RegisterRoomServer : global::ProtoBuf.IExtensible
  {
    public Msg_RL_RegisterRoomServer() {}
    
    private string _ServerName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ServerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ServerName
    {
      get { return _ServerName; }
      set { _ServerName = value; }
    }
    private int _MaxRoomNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"MaxRoomNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MaxRoomNum
    {
      get { return _MaxRoomNum; }
      set { _MaxRoomNum = value; }
    }
    private string _ServerIp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ServerIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ServerIp
    {
      get { return _ServerIp; }
      set { _ServerIp = value; }
    }
    private uint _ServerPort;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ServerPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ServerPort
    {
      get { return _ServerPort; }
      set { _ServerPort = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RL_ReplyReconnectUser")]
  public partial class Msg_RL_ReplyReconnectUser : global::ProtoBuf.IExtensible
  {
    public Msg_RL_ReplyReconnectUser() {}
    
    private ulong _UserGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserGuid
    {
      get { return _UserGuid; }
      set { _UserGuid = value; }
    }
    private int _RoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RoomID
    {
      get { return _RoomID; }
      set { _RoomID = value; }
    }
    private int _Result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ReconnectResultEnum")]
    public enum ReconnectResultEnum
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Drop", Value=0)]
      Drop = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotExist", Value=1)]
      NotExist = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Online", Value=2)]
      Online = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RL_RoomServerUpdateInfo")]
  public partial class Msg_RL_RoomServerUpdateInfo : global::ProtoBuf.IExtensible
  {
    public Msg_RL_RoomServerUpdateInfo() {}
    
    private string _ServerName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ServerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ServerName
    {
      get { return _ServerName; }
      set { _ServerName = value; }
    }
    private int _IdleRoomNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"IdleRoomNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int IdleRoomNum
    {
      get { return _IdleRoomNum; }
      set { _IdleRoomNum = value; }
    }
    private int _UserNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"UserNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int UserNum
    {
      get { return _UserNum; }
      set { _UserNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RL_UserDrop")]
  public partial class Msg_RL_UserDrop : global::ProtoBuf.IExtensible
  {
    public Msg_RL_UserDrop() {}
    
    private ulong _UserGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserGuid
    {
      get { return _UserGuid; }
      set { _UserGuid = value; }
    }
    private int _RoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RoomID
    {
      get { return _RoomID; }
      set { _RoomID = value; }
    }
    private bool _IsBattleEnd;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"IsBattleEnd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsBattleEnd
    {
      get { return _IsBattleEnd; }
      set { _IsBattleEnd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RL_UserLobbyItemInfo")]
  public partial class Msg_RL_UserLobbyItemInfo : global::ProtoBuf.IExtensible
  {
    public Msg_RL_UserLobbyItemInfo() {}
    
    private int _ItemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ItemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ItemId
    {
      get { return _ItemId; }
      set { _ItemId = value; }
    }
    private int _ItemNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ItemNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ItemNum
    {
      get { return _ItemNum; }
      set { _ItemNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RL_UserQuit")]
  public partial class Msg_RL_UserQuit : global::ProtoBuf.IExtensible
  {
    public Msg_RL_UserQuit() {}
    
    private ulong _UserGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UserGuid
    {
      get { return _UserGuid; }
      set { _UserGuid = value; }
    }
    private int _RoomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RoomID
    {
      get { return _RoomID; }
      set { _RoomID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}