//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoFiles/DataMessageDefine.proto
namespace GameFrameworkMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_DL_Connect")]
  public partial class Msg_DL_Connect : global::ProtoBuf.IExtensible
  {
    public Msg_DL_Connect() {}
    
    private bool _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private string _Error = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Error
    {
      get { return _Error; }
      set { _Error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_DL_LoadResult")]
  public partial class Msg_DL_LoadResult : global::ProtoBuf.IExtensible
  {
    public Msg_DL_LoadResult() {}
    
    private int _MsgId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MsgId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MsgId
    {
      get { return _MsgId; }
      set { _MsgId = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _PrimaryKeys = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"PrimaryKeys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> PrimaryKeys
    {
      get { return _PrimaryKeys; }
    }
  
    private long _SerialNo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SerialNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long SerialNo
    {
      get { return _SerialNo; }
      set { _SerialNo = value; }
    }
    private GameFrameworkMessage.Msg_DL_LoadResult.ErrorNoEnum _ErrorNo;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ErrorNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.Msg_DL_LoadResult.ErrorNoEnum ErrorNo
    {
      get { return _ErrorNo; }
      set { _ErrorNo = value; }
    }
    private string _ErrorInfo = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ErrorInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ErrorInfo
    {
      get { return _ErrorInfo; }
      set { _ErrorInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<GameFrameworkMessage.Msg_DL_SingleRowResult> _Results = new global::System.Collections.Generic.List<GameFrameworkMessage.Msg_DL_SingleRowResult>();
    [global::ProtoBuf.ProtoMember(6, Name=@"Results", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameFrameworkMessage.Msg_DL_SingleRowResult> Results
    {
      get { return _Results; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorNoEnum")]
    public enum ErrorNoEnum
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Exception", Value=-1)]
      Exception = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Success", Value=0)]
      Success = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotFound", Value=1)]
      NotFound = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PrepError", Value=2)]
      PrepError = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PostError", Value=3)]
      PostError = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TimeoutError", Value=4)]
      TimeoutError = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Undone", Value=5)]
      Undone = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_DL_SaveResult")]
  public partial class Msg_DL_SaveResult : global::ProtoBuf.IExtensible
  {
    public Msg_DL_SaveResult() {}
    
    private int _MsgId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MsgId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MsgId
    {
      get { return _MsgId; }
      set { _MsgId = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _PrimaryKeys = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"PrimaryKeys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> PrimaryKeys
    {
      get { return _PrimaryKeys; }
    }
  
    private long _SerialNo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SerialNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long SerialNo
    {
      get { return _SerialNo; }
      set { _SerialNo = value; }
    }
    private GameFrameworkMessage.Msg_DL_SaveResult.ErrorNoEnum _ErrorNo;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ErrorNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.Msg_DL_SaveResult.ErrorNoEnum ErrorNo
    {
      get { return _ErrorNo; }
      set { _ErrorNo = value; }
    }
    private string _ErrorInfo = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ErrorInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ErrorInfo
    {
      get { return _ErrorInfo; }
      set { _ErrorInfo = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ErrorNoEnum")]
    public enum ErrorNoEnum
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Exception", Value=-1)]
      Exception = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Success", Value=0)]
      Success = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotFound", Value=1)]
      NotFound = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PrepError", Value=2)]
      PrepError = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PostError", Value=3)]
      PostError = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TimeoutError", Value=4)]
      TimeoutError = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_DL_SingleRowResult")]
  public partial class Msg_DL_SingleRowResult : global::ProtoBuf.IExtensible
  {
    public Msg_DL_SingleRowResult() {}
    
    private int _MsgId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MsgId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MsgId
    {
      get { return _MsgId; }
      set { _MsgId = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _PrimaryKeys = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"PrimaryKeys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> PrimaryKeys
    {
      get { return _PrimaryKeys; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _ForeignKeys = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ForeignKeys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> ForeignKeys
    {
      get { return _ForeignKeys; }
    }
  
    private int _DataVersion;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"DataVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int DataVersion
    {
      get { return _DataVersion; }
      set { _DataVersion = value; }
    }
    private byte[] _Data = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LD_Connect")]
  public partial class Msg_LD_Connect : global::ProtoBuf.IExtensible
  {
    public Msg_LD_Connect() {}
    
    private string _ClientName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ClientName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ClientName
    {
      get { return _ClientName; }
      set { _ClientName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LD_Load")]
  public partial class Msg_LD_Load : global::ProtoBuf.IExtensible
  {
    public Msg_LD_Load() {}
    
    private int _MsgId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MsgId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MsgId
    {
      get { return _MsgId; }
      set { _MsgId = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _PrimaryKeys = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"PrimaryKeys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> PrimaryKeys
    {
      get { return _PrimaryKeys; }
    }
  
    private long _SerialNo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SerialNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long SerialNo
    {
      get { return _SerialNo; }
      set { _SerialNo = value; }
    }
    private readonly global::System.Collections.Generic.List<GameFrameworkMessage.Msg_LD_SingleLoadRequest> _LoadRequests = new global::System.Collections.Generic.List<GameFrameworkMessage.Msg_LD_SingleLoadRequest>();
    [global::ProtoBuf.ProtoMember(4, Name=@"LoadRequests", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameFrameworkMessage.Msg_LD_SingleLoadRequest> LoadRequests
    {
      get { return _LoadRequests; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LD_Save")]
  public partial class Msg_LD_Save : global::ProtoBuf.IExtensible
  {
    public Msg_LD_Save() {}
    
    private int _MsgId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MsgId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MsgId
    {
      get { return _MsgId; }
      set { _MsgId = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _PrimaryKeys = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"PrimaryKeys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> PrimaryKeys
    {
      get { return _PrimaryKeys; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _ForeignKeys = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ForeignKeys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> ForeignKeys
    {
      get { return _ForeignKeys; }
    }
  
    private long _SerialNo;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"SerialNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long SerialNo
    {
      get { return _SerialNo; }
      set { _SerialNo = value; }
    }
    private byte[] _Data = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LD_SingleLoadRequest")]
  public partial class Msg_LD_SingleLoadRequest : global::ProtoBuf.IExtensible
  {
    public Msg_LD_SingleLoadRequest() {}
    
    private int _MsgId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MsgId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MsgId
    {
      get { return _MsgId; }
      set { _MsgId = value; }
    }
    private GameFrameworkMessage.Msg_LD_SingleLoadRequest.LoadTypeEnum _LoadType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"LoadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.Msg_LD_SingleLoadRequest.LoadTypeEnum LoadType
    {
      get { return _LoadType; }
      set { _LoadType = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _Keys = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Keys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> Keys
    {
      get { return _Keys; }
    }
  
    private int _Start = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Start
    {
      get { return _Start; }
      set { _Start = value; }
    }
    private int _Count = (int)-1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int Count
    {
      get { return _Count; }
      set { _Count = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"LoadTypeEnum")]
    public enum LoadTypeEnum
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoadAll", Value=0)]
      LoadAll = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoadSingle", Value=1)]
      LoadSingle = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoadMulti", Value=2)]
      LoadMulti = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}