// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: DataMessageDefine.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace GameFrameworkMessage
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_DL_Connect : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool Result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Error
        {
            get => __pbn__Error ?? "";
            set => __pbn__Error = value;
        }
        public bool ShouldSerializeError() => __pbn__Error != null;
        public void ResetError() => __pbn__Error = null;
        private string __pbn__Error;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_DL_LoadResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int MsgId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<string> PrimaryKeys { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public long SerialNo { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public ErrorNoEnum ErrorNo { get; set; } = ErrorNoEnum.Exception;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ErrorInfo
        {
            get => __pbn__ErrorInfo ?? "";
            set => __pbn__ErrorInfo = value;
        }
        public bool ShouldSerializeErrorInfo() => __pbn__ErrorInfo != null;
        public void ResetErrorInfo() => __pbn__ErrorInfo = null;
        private string __pbn__ErrorInfo;

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<Msg_DL_SingleRowResult> Results { get; } = new global::System.Collections.Generic.List<Msg_DL_SingleRowResult>();

        [global::ProtoBuf.ProtoContract()]
        public enum ErrorNoEnum
        {
            Exception = -1,
            Success = 0,
            NotFound = 1,
            PrepError = 2,
            PostError = 3,
            TimeoutError = 4,
            Undone = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_DL_SaveResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int MsgId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<string> PrimaryKeys { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public long SerialNo { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public ErrorNoEnum ErrorNo { get; set; } = ErrorNoEnum.Exception;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ErrorInfo
        {
            get => __pbn__ErrorInfo ?? "";
            set => __pbn__ErrorInfo = value;
        }
        public bool ShouldSerializeErrorInfo() => __pbn__ErrorInfo != null;
        public void ResetErrorInfo() => __pbn__ErrorInfo = null;
        private string __pbn__ErrorInfo;

        [global::ProtoBuf.ProtoContract()]
        public enum ErrorNoEnum
        {
            Exception = -1,
            Success = 0,
            NotFound = 1,
            PrepError = 2,
            PostError = 3,
            TimeoutError = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_DL_SingleRowResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int MsgId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<string> PrimaryKeys { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<string> ForeignKeys { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int DataVersion { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public byte[] Data
        {
            get => __pbn__Data;
            set => __pbn__Data = value;
        }
        public bool ShouldSerializeData() => __pbn__Data != null;
        public void ResetData() => __pbn__Data = null;
        private byte[] __pbn__Data;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_LD_Connect : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string ClientName { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_LD_Load : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int MsgId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<string> PrimaryKeys { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public long SerialNo { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<Msg_LD_SingleLoadRequest> LoadRequests { get; } = new global::System.Collections.Generic.List<Msg_LD_SingleLoadRequest>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_LD_Save : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int MsgId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<string> PrimaryKeys { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<string> ForeignKeys { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public long SerialNo { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public byte[] Data
        {
            get => __pbn__Data;
            set => __pbn__Data = value;
        }
        public bool ShouldSerializeData() => __pbn__Data != null;
        public void ResetData() => __pbn__Data = null;
        private byte[] __pbn__Data;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_LD_SingleLoadRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int MsgId { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public LoadTypeEnum LoadType { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<string> Keys { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(4)]
        public int Start
        {
            get => __pbn__Start.GetValueOrDefault();
            set => __pbn__Start = value;
        }
        public bool ShouldSerializeStart() => __pbn__Start != null;
        public void ResetStart() => __pbn__Start = null;
        private int? __pbn__Start;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int Count
        {
            get => __pbn__Count ?? -1;
            set => __pbn__Count = value;
        }
        public bool ShouldSerializeCount() => __pbn__Count != null;
        public void ResetCount() => __pbn__Count = null;
        private int? __pbn__Count;

        [global::ProtoBuf.ProtoContract()]
        public enum LoadTypeEnum
        {
            LoadAll = 0,
            LoadSingle = 1,
            LoadMulti = 2,
        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
