// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: LobbyMsg.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace GameFrameworkMessage
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountLogin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string m_AccountId { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string m_Password { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string m_ClientInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountLoginResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string m_AccountId { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public AccountLoginResultEnum m_Result { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public ulong m_UserGuid { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum AccountLoginResultEnum
        {
            Success = 0,
            FirstLogin = 1,
            Error = 2,
            Wait = 3,
            Banned = 4,
            AlreadyOnline = 5,
            Queueing = 6,
            QueueFull = 7,
            Failed = 8,
            Nonactivated = 9,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountLogout : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangeName : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string m_Nickname { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangeNameResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ChangeNameResultEnum m_Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string m_Nickname { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum ChangeNameResultEnum
        {
            Success = 0,
            NicknameError = 1,
            UnknownError = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangeSceneRoom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int m_SceneId
        {
            get => __pbn__m_SceneId.GetValueOrDefault();
            set => __pbn__m_SceneId = value;
        }
        public bool ShouldSerializem_SceneId() => __pbn__m_SceneId != null;
        public void Resetm_SceneId() => __pbn__m_SceneId = null;
        private int? __pbn__m_SceneId;

        [global::ProtoBuf.ProtoMember(2)]
        public int m_RoomId
        {
            get => __pbn__m_RoomId.GetValueOrDefault();
            set => __pbn__m_RoomId = value;
        }
        public bool ShouldSerializem_RoomId() => __pbn__m_RoomId != null;
        public void Resetm_RoomId() => __pbn__m_RoomId = null;
        private int? __pbn__m_RoomId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DirectLogin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EnterScene : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int m_SceneId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int m_RoomId
        {
            get => __pbn__m_RoomId.GetValueOrDefault();
            set => __pbn__m_RoomId = value;
        }
        public bool ShouldSerializem_RoomId() => __pbn__m_RoomId != null;
        public void Resetm_RoomId() => __pbn__m_RoomId = null;
        private int? __pbn__m_RoomId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EnterSceneResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string server_ip
        {
            get => __pbn__server_ip ?? "";
            set => __pbn__server_ip = value;
        }
        public bool ShouldSerializeserver_ip() => __pbn__server_ip != null;
        public void Resetserver_ip() => __pbn__server_ip = null;
        private string __pbn__server_ip;

        [global::ProtoBuf.ProtoMember(3)]
        public uint server_port
        {
            get => __pbn__server_port.GetValueOrDefault();
            set => __pbn__server_port = value;
        }
        public bool ShouldSerializeserver_port() => __pbn__server_port != null;
        public void Resetserver_port() => __pbn__server_port = null;
        private uint? __pbn__server_port;

        [global::ProtoBuf.ProtoMember(4)]
        public uint key
        {
            get => __pbn__key.GetValueOrDefault();
            set => __pbn__key = value;
        }
        public bool ShouldSerializekey() => __pbn__key != null;
        public void Resetkey() => __pbn__key = null;
        private uint? __pbn__key;

        [global::ProtoBuf.ProtoMember(5)]
        public int camp_id
        {
            get => __pbn__camp_id.GetValueOrDefault();
            set => __pbn__camp_id = value;
        }
        public bool ShouldSerializecamp_id() => __pbn__camp_id != null;
        public void Resetcamp_id() => __pbn__camp_id = null;
        private int? __pbn__camp_id;

        [global::ProtoBuf.ProtoMember(6)]
        public int scene_type
        {
            get => __pbn__scene_type.GetValueOrDefault();
            set => __pbn__scene_type = value;
        }
        public bool ShouldSerializescene_type() => __pbn__scene_type != null;
        public void Resetscene_type() => __pbn__scene_type = null;
        private int? __pbn__scene_type;

        [global::ProtoBuf.ProtoMember(7)]
        public int prime
        {
            get => __pbn__prime.GetValueOrDefault();
            set => __pbn__prime = value;
        }
        public bool ShouldSerializeprime() => __pbn__prime != null;
        public void Resetprime() => __pbn__prime = null;
        private int? __pbn__prime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FriendInfoForMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong FriendGuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string FriendNickname { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public long QQ { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public long weixin { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public bool IsBlack { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetQueueingCount : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GmCode : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string m_Content { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemInfoForMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong ItemGuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int ItemId { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int ItemNum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KickUser : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Logout : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MailInfoForMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool m_AlreadyRead { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong m_MailGuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int m_Module { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public string m_Title { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public string m_Sender { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public string m_SendTime { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public string m_Text { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public global::System.Collections.Generic.List<MailItemForMessage> m_Items { get; } = new global::System.Collections.Generic.List<MailItemForMessage>();

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public int m_Money { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public int m_Gold { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MailItemForMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int m_ItemId { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int m_ItemNum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MemberInfoForMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int Hero { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CL_AddFriend : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string m_FriendNickname { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CL_DeleteMail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong m_MailGuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CL_DiscardItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong ItemGuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CL_GetMailList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CL_MarkBlack : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong m_FriendGuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CL_ReadMail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong m_MailGuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CL_ReceiveMail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong m_MailGuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CL_RemoveFriend : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong m_FriendGuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CL_UseItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int ItemId { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int ItemNum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CLC_StoryMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string m_MsgId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<MessageArg> m_Args { get; } = new global::System.Collections.Generic.List<MessageArg>();

        [global::ProtoBuf.ProtoContract()]
        public partial class MessageArg : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public LobbyArgType val_type { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public string str_val { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_LC_AddFriend : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public FriendInfoForMessage m_FriendInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_LC_HighlightPrompt : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string dict_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<string> argument { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_LC_LackOfSpace : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool m_Succeed { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int m_ReceiveNum { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int m_FreeNum { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public ulong m_MailGuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_LC_MarkBlack : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong m_FriendGuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_LC_NotifyNewMail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_LC_PublishEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool is_logic_event { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string ev_name { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string group { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<EventArg> args { get; } = new global::System.Collections.Generic.List<EventArg>();

        [global::ProtoBuf.ProtoContract()]
        public partial class EventArg : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public LobbyArgType val_type { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public string str_val { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_LC_RemoveFriend : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong m_FriendGuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_LC_SendGfxMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool is_with_tag { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string msg { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<EventArg> args { get; } = new global::System.Collections.Generic.List<EventArg>();

        [global::ProtoBuf.ProtoContract()]
        public partial class EventArg : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public LobbyArgType val_type { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public string str_val { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_LC_SyncFriendList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<FriendInfoForMessage> m_Friends { get; } = new global::System.Collections.Generic.List<FriendInfoForMessage>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_LC_SyncItemList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<ItemInfoForMessage> m_Items { get; } = new global::System.Collections.Generic.List<ItemInfoForMessage>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_LC_SyncMailList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<MailInfoForMessage> m_Mails { get; } = new global::System.Collections.Generic.List<MailInfoForMessage>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_LC_SyncMemberList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<MemberInfoForMessage> m_Members { get; } = new global::System.Collections.Generic.List<MemberInfoForMessage>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_LC_SyncRoleInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int HeroId { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int Money { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int Gold { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NodeMessageWithAccount : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string m_Account { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NodeMessageWithAccountAndGuid : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string m_Account { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong m_Guid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NodeMessageWithGuid : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong m_Guid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NodeRegister : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string m_Name { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NodeRegisterResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool m_IsOk { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QueueingCountResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int m_QueueingCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuitRoom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool m_IsQuitRoom { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestNickname : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestNicknameResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<string> m_Nicknames { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestSceneRoomInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestSceneRoomList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleEnter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string m_Nickname
        {
            get => __pbn__m_Nickname ?? "";
            set => __pbn__m_Nickname = value;
        }
        public bool ShouldSerializem_Nickname() => __pbn__m_Nickname != null;
        public void Resetm_Nickname() => __pbn__m_Nickname = null;
        private string __pbn__m_Nickname;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleEnterResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public RoleEnterResultEnum Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string Nickname { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int HeroId { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int Money { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public int Gold { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public int SceneId { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public int WorldId { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public global::System.Collections.Generic.List<MemberInfoForMessage> Members { get; } = new global::System.Collections.Generic.List<MemberInfoForMessage>();

        [global::ProtoBuf.ProtoMember(10)]
        public global::System.Collections.Generic.List<ItemInfoForMessage> Items { get; } = new global::System.Collections.Generic.List<ItemInfoForMessage>();

        [global::ProtoBuf.ProtoMember(11)]
        public global::System.Collections.Generic.List<FriendInfoForMessage> Friends { get; } = new global::System.Collections.Generic.List<FriendInfoForMessage>();

        [global::ProtoBuf.ProtoContract()]
        public enum RoleEnterResultEnum
        {
            Success = 0,
            Wait = 1,
            Reconnect = 2,
            UnknownError = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServerShutdown : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TooManyOperations : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserHeartbeat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VersionVerify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VersionVerifyResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int m_Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int m_EnableLog { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public uint m_ShopMask { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum LobbyArgType
    {
        NULL = 0,
        INT = 1,
        FLOAT = 2,
        STRING = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
