//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoFiles/LobbyGmMsg.proto
namespace GameFrameworkMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GmUserBasic")]
  public partial class GmUserBasic : global::ProtoBuf.IExtensible
  {
    public GmUserBasic() {}
    
    private int _m_HeroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_HeroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_HeroId
    {
      get { return _m_HeroId; }
      set { _m_HeroId = value; }
    }
    private int _m_Level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_Level
    {
      get { return _m_Level; }
      set { _m_Level = value; }
    }
    private int _m_Vip;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_Vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_Vip
    {
      get { return _m_Vip; }
      set { _m_Vip = value; }
    }
    private int _m_Money;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_Money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_Money
    {
      get { return _m_Money; }
      set { _m_Money = value; }
    }
    private int _m_Gold;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"m_Gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_Gold
    {
      get { return _m_Gold; }
      set { _m_Gold = value; }
    }
    private string _m_CreateTime;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"m_CreateTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_CreateTime
    {
      get { return _m_CreateTime; }
      set { _m_CreateTime = value; }
    }
    private string _m_LastLogoutTime;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"m_LastLogoutTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_LastLogoutTime
    {
      get { return _m_LastLogoutTime; }
      set { _m_LastLogoutTime = value; }
    }
    private int _m_GoldCash;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"m_GoldCash", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_GoldCash
    {
      get { return _m_GoldCash; }
      set { _m_GoldCash = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GmUserInfo")]
  public partial class GmUserInfo : global::ProtoBuf.IExtensible
  {
    public GmUserInfo() {}
    
    private ulong _m_Guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong m_Guid
    {
      get { return _m_Guid; }
      set { _m_Guid = value; }
    }
    private string _m_AccountId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_AccountId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_AccountId
    {
      get { return _m_AccountId; }
      set { _m_AccountId = value; }
    }
    private string _m_Nickname;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_Nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_Nickname
    {
      get { return _m_Nickname; }
      set { _m_Nickname = value; }
    }
    private GameFrameworkMessage.GmStateEnum _m_UserState;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_UserState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.GmStateEnum m_UserState
    {
      get { return _m_UserState; }
      set { _m_UserState = value; }
    }
    private GameFrameworkMessage.GmUserBasic _m_UserBasic = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"m_UserBasic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GameFrameworkMessage.GmUserBasic m_UserBasic
    {
      get { return _m_UserBasic; }
      set { _m_UserBasic = value; }
    }
    private readonly global::System.Collections.Generic.List<GameFrameworkMessage.ItemDataMsg> _m_UserEquips = new global::System.Collections.Generic.List<GameFrameworkMessage.ItemDataMsg>();
    [global::ProtoBuf.ProtoMember(6, Name=@"m_UserEquips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameFrameworkMessage.ItemDataMsg> m_UserEquips
    {
      get { return _m_UserEquips; }
    }
  
    private readonly global::System.Collections.Generic.List<GameFrameworkMessage.ItemDataMsg> _m_UserBagItems = new global::System.Collections.Generic.List<GameFrameworkMessage.ItemDataMsg>();
    [global::ProtoBuf.ProtoMember(7, Name=@"m_UserBagItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameFrameworkMessage.ItemDataMsg> m_UserBagItems
    {
      get { return _m_UserBagItems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemDataMsg")]
  public partial class ItemDataMsg : global::ProtoBuf.IExtensible
  {
    public ItemDataMsg() {}
    
    private ulong _Guid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Guid
    {
      get { return _Guid; }
      set { _Guid = value; }
    }
    private int _ItemId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ItemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ItemId
    {
      get { return _ItemId; }
      set { _ItemId = value; }
    }
    private int _Level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private int _Experience = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Experience", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Experience
    {
      get { return _Experience; }
      set { _Experience = value; }
    }
    private int _Num = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Num
    {
      get { return _Num; }
      set { _Num = value; }
    }
    private int _AppendProperty = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"AppendProperty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AppendProperty
    {
      get { return _AppendProperty; }
      set { _AppendProperty = value; }
    }
    private int _EnhanceStarLevel = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"EnhanceStarLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int EnhanceStarLevel
    {
      get { return _EnhanceStarLevel; }
      set { _EnhanceStarLevel = value; }
    }
    private int _StrengthLevel = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"StrengthLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int StrengthLevel
    {
      get { return _StrengthLevel; }
      set { _StrengthLevel = value; }
    }
    private int _StrengthFailCount = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"StrengthFailCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int StrengthFailCount
    {
      get { return _StrengthFailCount; }
      set { _StrengthFailCount = value; }
    }
    private bool _IsCanTrade = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"IsCanTrade", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsCanTrade
    {
      get { return _IsCanTrade; }
      set { _IsCanTrade = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CL_GmAddExp")]
  public partial class Msg_CL_GmAddExp : global::ProtoBuf.IExtensible
  {
    public Msg_CL_GmAddExp() {}
    
    private string _m_Nick;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_Nick
    {
      get { return _m_Nick; }
      set { _m_Nick = value; }
    }
    private int _m_Exp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_Exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_Exp
    {
      get { return _m_Exp; }
      set { _m_Exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CL_GmCode")]
  public partial class Msg_CL_GmCode : global::ProtoBuf.IExtensible
  {
    public Msg_CL_GmCode() {}
    
    private string _m_Nick;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_Nick
    {
      get { return _m_Nick; }
      set { _m_Nick = value; }
    }
    private string _m_Content;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_Content
    {
      get { return _m_Content; }
      set { _m_Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CL_GmForbidChat")]
  public partial class Msg_CL_GmForbidChat : global::ProtoBuf.IExtensible
  {
    public Msg_CL_GmForbidChat() {}
    
    private string _m_Nickname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_Nickname
    {
      get { return _m_Nickname; }
      set { _m_Nickname = value; }
    }
    private bool _m_IsForbid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_IsForbid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool m_IsForbid
    {
      get { return _m_IsForbid; }
      set { _m_IsForbid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CL_GmGeneralOperation")]
  public partial class Msg_CL_GmGeneralOperation : global::ProtoBuf.IExtensible
  {
    public Msg_CL_GmGeneralOperation() {}
    
    private int _m_OperationType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_OperationType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_OperationType
    {
      get { return _m_OperationType; }
      set { _m_OperationType = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _m_Params = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"m_Params", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> m_Params
    {
      get { return _m_Params; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CL_GmHomeNotice")]
  public partial class Msg_CL_GmHomeNotice : global::ProtoBuf.IExtensible
  {
    public Msg_CL_GmHomeNotice() {}
    
    private string _m_Content;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_Content
    {
      get { return _m_Content; }
      set { _m_Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CL_GmKickUser")]
  public partial class Msg_CL_GmKickUser : global::ProtoBuf.IExtensible
  {
    public Msg_CL_GmKickUser() {}
    
    private string _m_Nickname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_Nickname
    {
      get { return _m_Nickname; }
      set { _m_Nickname = value; }
    }
    private int _m_LockMinutes;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_LockMinutes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_LockMinutes
    {
      get { return _m_LockMinutes; }
      set { _m_LockMinutes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CL_GmLockUser")]
  public partial class Msg_CL_GmLockUser : global::ProtoBuf.IExtensible
  {
    public Msg_CL_GmLockUser() {}
    
    private string _m_AccountId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_AccountId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_AccountId
    {
      get { return _m_AccountId; }
      set { _m_AccountId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CL_GmQueryAccount")]
  public partial class Msg_CL_GmQueryAccount : global::ProtoBuf.IExtensible
  {
    public Msg_CL_GmQueryAccount() {}
    
    private string _m_QueryAccount;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_QueryAccount", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_QueryAccount
    {
      get { return _m_QueryAccount; }
      set { _m_QueryAccount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CL_GmQueryUserByFuzzyNickname")]
  public partial class Msg_CL_GmQueryUserByFuzzyNickname : global::ProtoBuf.IExtensible
  {
    public Msg_CL_GmQueryUserByFuzzyNickname() {}
    
    private string _m_QueryNickname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_QueryNickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_QueryNickname
    {
      get { return _m_QueryNickname; }
      set { _m_QueryNickname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CL_GmQueryUserByGuid")]
  public partial class Msg_CL_GmQueryUserByGuid : global::ProtoBuf.IExtensible
  {
    public Msg_CL_GmQueryUserByGuid() {}
    
    private ulong _m_QueryGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_QueryGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong m_QueryGuid
    {
      get { return _m_QueryGuid; }
      set { _m_QueryGuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CL_GmQueryUserByNickname")]
  public partial class Msg_CL_GmQueryUserByNickname : global::ProtoBuf.IExtensible
  {
    public Msg_CL_GmQueryUserByNickname() {}
    
    private string _m_QueryNickname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_QueryNickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_QueryNickname
    {
      get { return _m_QueryNickname; }
      set { _m_QueryNickname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CL_GmUnlockUser")]
  public partial class Msg_CL_GmUnlockUser : global::ProtoBuf.IExtensible
  {
    public Msg_CL_GmUnlockUser() {}
    
    private string _m_AccountId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_AccountId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_AccountId
    {
      get { return _m_AccountId; }
      set { _m_AccountId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CL_GmUpdateMaxUserCount")]
  public partial class Msg_CL_GmUpdateMaxUserCount : global::ProtoBuf.IExtensible
  {
    public Msg_CL_GmUpdateMaxUserCount() {}
    
    private int _m_MaxUserCount;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_MaxUserCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_MaxUserCount
    {
      get { return _m_MaxUserCount; }
      set { _m_MaxUserCount = value; }
    }
    private int _m_MaxQueueingCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_MaxQueueingCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_MaxQueueingCount
    {
      get { return _m_MaxQueueingCount; }
      set { _m_MaxQueueingCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CL_PublishNotice")]
  public partial class Msg_CL_PublishNotice : global::ProtoBuf.IExtensible
  {
    public Msg_CL_PublishNotice() {}
    
    private string _m_Content;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_Content
    {
      get { return _m_Content; }
      set { _m_Content = value; }
    }
    private int _m_RollNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_RollNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_RollNum
    {
      get { return _m_RollNum; }
      set { _m_RollNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CL_SendMail")]
  public partial class Msg_CL_SendMail : global::ProtoBuf.IExtensible
  {
    public Msg_CL_SendMail() {}
    
    private string _m_Receiver;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Receiver", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_Receiver
    {
      get { return _m_Receiver; }
      set { _m_Receiver = value; }
    }
    private string _m_Title;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_Title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_Title
    {
      get { return _m_Title; }
      set { _m_Title = value; }
    }
    private string _m_Text;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_Text
    {
      get { return _m_Text; }
      set { _m_Text = value; }
    }
    private int _m_ExpiryDate;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_ExpiryDate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_ExpiryDate
    {
      get { return _m_ExpiryDate; }
      set { _m_ExpiryDate = value; }
    }
    private int _m_LevelDemand;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"m_LevelDemand", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_LevelDemand
    {
      get { return _m_LevelDemand; }
      set { _m_LevelDemand = value; }
    }
    private int _m_ItemId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"m_ItemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_ItemId
    {
      get { return _m_ItemId; }
      set { _m_ItemId = value; }
    }
    private int _m_ItemNum;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"m_ItemNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_ItemNum
    {
      get { return _m_ItemNum; }
      set { _m_ItemNum = value; }
    }
    private int _m_Money;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"m_Money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_Money
    {
      get { return _m_Money; }
      set { _m_Money = value; }
    }
    private int _m_Gold;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"m_Gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_Gold
    {
      get { return _m_Gold; }
      set { _m_Gold = value; }
    }
    private int _m_Stamina;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"m_Stamina", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_Stamina
    {
      get { return _m_Stamina; }
      set { _m_Stamina = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LC_GmAddExp")]
  public partial class Msg_LC_GmAddExp : global::ProtoBuf.IExtensible
  {
    public Msg_LC_GmAddExp() {}
    
    private int _m_Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_Result
    {
      get { return _m_Result; }
      set { _m_Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LC_GmForbidChat")]
  public partial class Msg_LC_GmForbidChat : global::ProtoBuf.IExtensible
  {
    public Msg_LC_GmForbidChat() {}
    
    private GameFrameworkMessage.GmResultEnum _m_Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.GmResultEnum m_Result
    {
      get { return _m_Result; }
      set { _m_Result = value; }
    }
    private string _m_Nickname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_Nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_Nickname
    {
      get { return _m_Nickname; }
      set { _m_Nickname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LC_GmGeneralOperation")]
  public partial class Msg_LC_GmGeneralOperation : global::ProtoBuf.IExtensible
  {
    public Msg_LC_GmGeneralOperation() {}
    
    private GameFrameworkMessage.GmResultEnum _m_Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.GmResultEnum m_Result
    {
      get { return _m_Result; }
      set { _m_Result = value; }
    }
    private int _m_OperationType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_OperationType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_OperationType
    {
      get { return _m_OperationType; }
      set { _m_OperationType = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _m_Params = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"m_Params", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> m_Params
    {
      get { return _m_Params; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LC_GmHomeNotice")]
  public partial class Msg_LC_GmHomeNotice : global::ProtoBuf.IExtensible
  {
    public Msg_LC_GmHomeNotice() {}
    
    private GameFrameworkMessage.GmResultEnum _m_Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.GmResultEnum m_Result
    {
      get { return _m_Result; }
      set { _m_Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LC_GmKickUser")]
  public partial class Msg_LC_GmKickUser : global::ProtoBuf.IExtensible
  {
    public Msg_LC_GmKickUser() {}
    
    private GameFrameworkMessage.GmResultEnum _m_Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.GmResultEnum m_Result
    {
      get { return _m_Result; }
      set { _m_Result = value; }
    }
    private string _m_Nickname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_Nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_Nickname
    {
      get { return _m_Nickname; }
      set { _m_Nickname = value; }
    }
    private long _m_KickedGuid = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"m_KickedGuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long m_KickedGuid
    {
      get { return _m_KickedGuid; }
      set { _m_KickedGuid = value; }
    }
    private string _m_KickedAccountId = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"m_KickedAccountId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string m_KickedAccountId
    {
      get { return _m_KickedAccountId; }
      set { _m_KickedAccountId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LC_GmLockUser")]
  public partial class Msg_LC_GmLockUser : global::ProtoBuf.IExtensible
  {
    public Msg_LC_GmLockUser() {}
    
    private GameFrameworkMessage.GmResultEnum _m_Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.GmResultEnum m_Result
    {
      get { return _m_Result; }
      set { _m_Result = value; }
    }
    private string _m_AccountId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_AccountId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_AccountId
    {
      get { return _m_AccountId; }
      set { _m_AccountId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LC_GmQueryAccount")]
  public partial class Msg_LC_GmQueryAccount : global::ProtoBuf.IExtensible
  {
    public Msg_LC_GmQueryAccount() {}
    
    private GameFrameworkMessage.GmResultEnum _m_Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.GmResultEnum m_Result
    {
      get { return _m_Result; }
      set { _m_Result = value; }
    }
    private string _m_QueryAccount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_QueryAccount", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_QueryAccount
    {
      get { return _m_QueryAccount; }
      set { _m_QueryAccount = value; }
    }
    private GameFrameworkMessage.GmStateEnum _m_AccountState = GameFrameworkMessage.GmStateEnum.Online;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"m_AccountState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(GameFrameworkMessage.GmStateEnum.Online)]
    public GameFrameworkMessage.GmStateEnum m_AccountState
    {
      get { return _m_AccountState; }
      set { _m_AccountState = value; }
    }
    private readonly global::System.Collections.Generic.List<GameFrameworkMessage.GmUserInfo> _m_Infos = new global::System.Collections.Generic.List<GameFrameworkMessage.GmUserInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"m_Infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameFrameworkMessage.GmUserInfo> m_Infos
    {
      get { return _m_Infos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LC_GmQueryUser")]
  public partial class Msg_LC_GmQueryUser : global::ProtoBuf.IExtensible
  {
    public Msg_LC_GmQueryUser() {}
    
    private GameFrameworkMessage.GmResultEnum _m_Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.GmResultEnum m_Result
    {
      get { return _m_Result; }
      set { _m_Result = value; }
    }
    private GameFrameworkMessage.GmUserInfo _m_Info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"m_Info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GameFrameworkMessage.GmUserInfo m_Info
    {
      get { return _m_Info; }
      set { _m_Info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LC_GmQueryUserByFuzzyNickname")]
  public partial class Msg_LC_GmQueryUserByFuzzyNickname : global::ProtoBuf.IExtensible
  {
    public Msg_LC_GmQueryUserByFuzzyNickname() {}
    
    private GameFrameworkMessage.GmResultEnum _m_Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.GmResultEnum m_Result
    {
      get { return _m_Result; }
      set { _m_Result = value; }
    }
    private string _m_QueryNickname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_QueryNickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_QueryNickname
    {
      get { return _m_QueryNickname; }
      set { _m_QueryNickname = value; }
    }
    private readonly global::System.Collections.Generic.List<GameFrameworkMessage.GmUserInfo> _m_Infos = new global::System.Collections.Generic.List<GameFrameworkMessage.GmUserInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"m_Infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameFrameworkMessage.GmUserInfo> m_Infos
    {
      get { return _m_Infos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LC_GmUnlockUser")]
  public partial class Msg_LC_GmUnlockUser : global::ProtoBuf.IExtensible
  {
    public Msg_LC_GmUnlockUser() {}
    
    private GameFrameworkMessage.GmResultEnum _m_Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.GmResultEnum m_Result
    {
      get { return _m_Result; }
      set { _m_Result = value; }
    }
    private string _m_AccountId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_AccountId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_AccountId
    {
      get { return _m_AccountId; }
      set { _m_AccountId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LC_PublishNotice")]
  public partial class Msg_LC_PublishNotice : global::ProtoBuf.IExtensible
  {
    public Msg_LC_PublishNotice() {}
    
    private GameFrameworkMessage.GmResultEnum _m_Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.GmResultEnum m_Result
    {
      get { return _m_Result; }
      set { _m_Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_LC_SendMail")]
  public partial class Msg_LC_SendMail : global::ProtoBuf.IExtensible
  {
    public Msg_LC_SendMail() {}
    
    private GameFrameworkMessage.GmResultEnum _m_Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.GmResultEnum m_Result
    {
      get { return _m_Result; }
      set { _m_Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GmResultEnum")]
    public enum GmResultEnum
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Success", Value=1)]
      Success = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Failed", Value=2)]
      Failed = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GmStateEnum")]
    public enum GmStateEnum
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Online", Value=1)]
      Online = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Offline", Value=2)]
      Offline = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Banned", Value=3)]
      Banned = 3
    }
  
}