// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: RoomMsg.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace GameFrameworkMessage
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CR_DlgClosed : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int dialog_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CR_Enter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CR_GmCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string content
        {
            get => __pbn__content ?? "";
            set => __pbn__content = value;
        }
        public bool ShouldSerializecontent() => __pbn__content != null;
        public void Resetcontent() => __pbn__content = null;
        private string __pbn__content;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CR_Observer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CR_Quit : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool is_force { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CR_ShakeHands : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint auth_key { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CR_Skill : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int role_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int skill_id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int target_id
        {
            get => __pbn__target_id.GetValueOrDefault();
            set => __pbn__target_id = value;
        }
        public bool ShouldSerializetarget_id() => __pbn__target_id != null;
        public void Resettarget_id() => __pbn__target_id = null;
        private int? __pbn__target_id;

        [global::ProtoBuf.ProtoMember(4)]
        public float target_dir
        {
            get => __pbn__target_dir.GetValueOrDefault();
            set => __pbn__target_dir = value;
        }
        public bool ShouldSerializetarget_dir() => __pbn__target_dir != null;
        public void Resettarget_dir() => __pbn__target_dir = null;
        private float? __pbn__target_dir;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CR_StopSkill : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CR_SwitchDebug : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool is_debug { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CR_UserMoveToPos : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public Position target_pos { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool is_stop
        {
            get => __pbn__is_stop.GetValueOrDefault();
            set => __pbn__is_stop = value;
        }
        public bool ShouldSerializeis_stop() => __pbn__is_stop != null;
        public void Resetis_stop() => __pbn__is_stop = null;
        private bool? __pbn__is_stop;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_CRC_StoryMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string m_MsgId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<MessageArg> m_Args { get; } = new global::System.Collections.Generic.List<MessageArg>();

        [global::ProtoBuf.ProtoContract()]
        public partial class MessageArg : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public ArgType val_type { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public string str_val { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_Ping : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public long send_ping_time { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_Pong : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public long send_ping_time { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public long send_pong_time { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_AddImpact : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int sender_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int target_id { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int impact_id { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int skill_id { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public int duration { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_AddSkill : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int obj_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int skill_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_AdjustPosition : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int role_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public float x { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public float z { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public float face_dir { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_CampChanged : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int obj_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int camp_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_ChangeScene : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int target_scene_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_CreateNpc : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int npc_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int unit_id { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public Position cur_pos { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public float face_direction { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public int link_id { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int camp_id
        {
            get => __pbn__camp_id.GetValueOrDefault();
            set => __pbn__camp_id = value;
        }
        public bool ShouldSerializecamp_id() => __pbn__camp_id != null;
        public void Resetcamp_id() => __pbn__camp_id = null;
        private int? __pbn__camp_id;

        [global::ProtoBuf.ProtoMember(7)]
        public int owner_id
        {
            get => __pbn__owner_id.GetValueOrDefault();
            set => __pbn__owner_id = value;
        }
        public bool ShouldSerializeowner_id() => __pbn__owner_id != null;
        public void Resetowner_id() => __pbn__owner_id = null;
        private int? __pbn__owner_id;

        [global::ProtoBuf.ProtoMember(8)]
        public int leader_id
        {
            get => __pbn__leader_id.GetValueOrDefault();
            set => __pbn__leader_id = value;
        }
        public bool ShouldSerializeleader_id() => __pbn__leader_id != null;
        public void Resetleader_id() => __pbn__leader_id = null;
        private int? __pbn__leader_id;

        [global::ProtoBuf.ProtoMember(9)]
        public uint key
        {
            get => __pbn__key.GetValueOrDefault();
            set => __pbn__key = value;
        }
        public bool ShouldSerializekey() => __pbn__key != null;
        public void Resetkey() => __pbn__key = null;
        private uint? __pbn__key;

        [global::ProtoBuf.ProtoMember(10)]
        public int level
        {
            get => __pbn__level.GetValueOrDefault();
            set => __pbn__level = value;
        }
        public bool ShouldSerializelevel() => __pbn__level != null;
        public void Resetlevel() => __pbn__level = null;
        private int? __pbn__level;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_DebugSpaceInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<DebugSpaceInfo> space_infos { get; } = new global::System.Collections.Generic.List<DebugSpaceInfo>();

        [global::ProtoBuf.ProtoContract()]
        public partial class DebugSpaceInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public int obj_id { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public bool is_player { get; set; }

            [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
            public float pos_x { get; set; }

            [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
            public float pos_z { get; set; }

            [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
            public float face_dir { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_DestroyNpc : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int npc_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_HighlightPrompt : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string dict_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<string> argument { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_ImpactDamage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int role_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int attacker_id { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int damage_status { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int hp { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int energy
        {
            get => __pbn__energy.GetValueOrDefault();
            set => __pbn__energy = value;
        }
        public bool ShouldSerializeenergy() => __pbn__energy != null;
        public void Resetenergy() => __pbn__energy = null;
        private int? __pbn__energy;

        [global::ProtoBuf.ProtoContract()]
        public enum Flag
        {
            IS_KILLER = 1,
            IS_CRITICAL = 2,
            IS_ORDINARY = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_LockFrame : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public float scale { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_NpcDead : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int npc_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_NpcFace : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int npc_id
        {
            get => __pbn__npc_id.GetValueOrDefault();
            set => __pbn__npc_id = value;
        }
        public bool ShouldSerializenpc_id() => __pbn__npc_id != null;
        public void Resetnpc_id() => __pbn__npc_id = null;
        private int? __pbn__npc_id;

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public float face_direction { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_NpcMove : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int npc_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public float velocity
        {
            get => __pbn__velocity.GetValueOrDefault();
            set => __pbn__velocity = value;
        }
        public bool ShouldSerializevelocity() => __pbn__velocity != null;
        public void Resetvelocity() => __pbn__velocity = null;
        private float? __pbn__velocity;

        [global::ProtoBuf.ProtoMember(3)]
        public Position cur_pos { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public Position target_pos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_NpcSkill : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int npc_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int skill_id { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public Position stand_pos { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public float face_direction { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public int target_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_NpcStopSkill : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int npc_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_PlayAnimation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int obj_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string anim_name { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_PublishEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool is_logic_event { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string ev_name { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string group { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<EventArg> args { get; } = new global::System.Collections.Generic.List<EventArg>();

        [global::ProtoBuf.ProtoContract()]
        public partial class EventArg : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public ArgType val_type { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public string str_val { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_RemoveImpact : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int obj_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int impact_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_RemoveSkill : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int obj_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int skill_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_SendGfxMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool is_with_tag { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string msg { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<EventArg> args { get; } = new global::System.Collections.Generic.List<EventArg>();

        [global::ProtoBuf.ProtoContract()]
        public partial class EventArg : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public ArgType val_type { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public string str_val { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_ShakeHands_Ret : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public RetType auth_result { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum RetType
        {
            SUCCESS = 0,
            ERROR = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_ShowDlg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int dialog_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_SyncNpcOwnerId : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int npc_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int owner_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Msg_RC_SyncProperty : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int role_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int hp { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int np { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int shield { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public int state { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Position : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public float x { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public float z { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum ArgType
    {
        NULL = 0,
        INT = 1,
        FLOAT = 2,
        STRING = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
