//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoFiles/RoomMsg.proto
namespace GameFrameworkMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EncodePosition")]
  public partial class EncodePosition : global::ProtoBuf.IExtensible
  {
    public EncodePosition() {}
    
    private int _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _z;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EncodePosition3D")]
  public partial class EncodePosition3D : global::ProtoBuf.IExtensible
  {
    public EncodePosition3D() {}
    
    private int _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CR_DlgClosed")]
  public partial class Msg_CR_DlgClosed : global::ProtoBuf.IExtensible
  {
    public Msg_CR_DlgClosed() {}
    
    private int _dialog_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dialog_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dialog_id
    {
      get { return _dialog_id; }
      set { _dialog_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CR_Enter")]
  public partial class Msg_CR_Enter : global::ProtoBuf.IExtensible
  {
    public Msg_CR_Enter() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CR_GiveUpBattle")]
  public partial class Msg_CR_GiveUpBattle : global::ProtoBuf.IExtensible
  {
    public Msg_CR_GiveUpBattle() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CR_GmCommand")]
  public partial class Msg_CR_GmCommand : global::ProtoBuf.IExtensible
  {
    public Msg_CR_GmCommand() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CR_Observer")]
  public partial class Msg_CR_Observer : global::ProtoBuf.IExtensible
  {
    public Msg_CR_Observer() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CR_OperateMode")]
  public partial class Msg_CR_OperateMode : global::ProtoBuf.IExtensible
  {
    public Msg_CR_OperateMode() {}
    
    private bool _isauto;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"isauto", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isauto
    {
      get { return _isauto; }
      set { _isauto = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CR_Quit")]
  public partial class Msg_CR_Quit : global::ProtoBuf.IExtensible
  {
    public Msg_CR_Quit() {}
    
    private bool _is_force;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"is_force", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_force
    {
      get { return _is_force; }
      set { _is_force = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CR_ShakeHands")]
  public partial class Msg_CR_ShakeHands : global::ProtoBuf.IExtensible
  {
    public Msg_CR_ShakeHands() {}
    
    private uint _auth_key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"auth_key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint auth_key
    {
      get { return _auth_key; }
      set { _auth_key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CR_Skill")]
  public partial class Msg_CR_Skill : global::ProtoBuf.IExtensible
  {
    public Msg_CR_Skill() {}
    
    private int _role_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"role_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int role_id
    {
      get { return _role_id; }
      set { _role_id = value; }
    }
    private int _skill_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private int _target_id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }
    private int _target_dir = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"target_dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int target_dir
    {
      get { return _target_dir; }
      set { _target_dir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CR_StopSkill")]
  public partial class Msg_CR_StopSkill : global::ProtoBuf.IExtensible
  {
    public Msg_CR_StopSkill() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CR_SwitchDebug")]
  public partial class Msg_CR_SwitchDebug : global::ProtoBuf.IExtensible
  {
    public Msg_CR_SwitchDebug() {}
    
    private bool _is_debug;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"is_debug", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_debug
    {
      get { return _is_debug; }
      set { _is_debug = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CR_UserMoveToPos")]
  public partial class Msg_CR_UserMoveToPos : global::ProtoBuf.IExtensible
  {
    public Msg_CR_UserMoveToPos() {}
    
    private ulong _target_pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"target_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong target_pos
    {
      get { return _target_pos; }
      set { _target_pos = value; }
    }
    private bool _is_stop = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"is_stop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_stop
    {
      get { return _is_stop; }
      set { _is_stop = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_CRC_StoryMessage")]
  public partial class Msg_CRC_StoryMessage : global::ProtoBuf.IExtensible
  {
    public Msg_CRC_StoryMessage() {}
    
    private string _m_MsgId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_MsgId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_MsgId
    {
      get { return _m_MsgId; }
      set { _m_MsgId = value; }
    }
    private readonly global::System.Collections.Generic.List<GameFrameworkMessage.Msg_CRC_StoryMessage.MessageArg> _m_Args = new global::System.Collections.Generic.List<GameFrameworkMessage.Msg_CRC_StoryMessage.MessageArg>();
    [global::ProtoBuf.ProtoMember(2, Name=@"m_Args", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameFrameworkMessage.Msg_CRC_StoryMessage.MessageArg> m_Args
    {
      get { return _m_Args; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageArg")]
  public partial class MessageArg : global::ProtoBuf.IExtensible
  {
    public MessageArg() {}
    
    private GameFrameworkMessage.ArgType _val_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"val_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.ArgType val_type
    {
      get { return _val_type; }
      set { _val_type = value; }
    }
    private string _str_val;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"str_val", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string str_val
    {
      get { return _str_val; }
      set { _str_val = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Ping")]
  public partial class Msg_Ping : global::ProtoBuf.IExtensible
  {
    public Msg_Ping() {}
    
    private long _send_ping_time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"send_ping_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long send_ping_time
    {
      get { return _send_ping_time; }
      set { _send_ping_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_Pong")]
  public partial class Msg_Pong : global::ProtoBuf.IExtensible
  {
    public Msg_Pong() {}
    
    private long _send_ping_time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"send_ping_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long send_ping_time
    {
      get { return _send_ping_time; }
      set { _send_ping_time = value; }
    }
    private long _send_pong_time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"send_pong_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long send_pong_time
    {
      get { return _send_pong_time; }
      set { _send_pong_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_AddImpact")]
  public partial class Msg_RC_AddImpact : global::ProtoBuf.IExtensible
  {
    public Msg_RC_AddImpact() {}
    
    private int _sender_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sender_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sender_id
    {
      get { return _sender_id; }
      set { _sender_id = value; }
    }
    private int _target_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }
    private int _impact_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"impact_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int impact_id
    {
      get { return _impact_id; }
      set { _impact_id = value; }
    }
    private int _skill_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private int _duration;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"duration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int duration
    {
      get { return _duration; }
      set { _duration = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_AddSkill")]
  public partial class Msg_RC_AddSkill : global::ProtoBuf.IExtensible
  {
    public Msg_RC_AddSkill() {}
    
    private int _obj_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"obj_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int obj_id
    {
      get { return _obj_id; }
      set { _obj_id = value; }
    }
    private int _skill_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_AdjustPosition")]
  public partial class Msg_RC_AdjustPosition : global::ProtoBuf.IExtensible
  {
    public Msg_RC_AdjustPosition() {}
    
    private int _role_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"role_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int role_id
    {
      get { return _role_id; }
      set { _role_id = value; }
    }
    private int _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int z
    {
      get { return _z; }
      set { _z = value; }
    }
    private int _face_dir;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"face_dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int face_dir
    {
      get { return _face_dir; }
      set { _face_dir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_CampChanged")]
  public partial class Msg_RC_CampChanged : global::ProtoBuf.IExtensible
  {
    public Msg_RC_CampChanged() {}
    
    private int _obj_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"obj_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int obj_id
    {
      get { return _obj_id; }
      set { _obj_id = value; }
    }
    private int _camp_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"camp_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int camp_id
    {
      get { return _camp_id; }
      set { _camp_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_ChangeScene")]
  public partial class Msg_RC_ChangeScene : global::ProtoBuf.IExtensible
  {
    public Msg_RC_ChangeScene() {}
    
    private int _target_scene_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"target_scene_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int target_scene_id
    {
      get { return _target_scene_id; }
      set { _target_scene_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_CreateNpc")]
  public partial class Msg_RC_CreateNpc : global::ProtoBuf.IExtensible
  {
    public Msg_RC_CreateNpc() {}
    
    private int _npc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"npc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int npc_id
    {
      get { return _npc_id; }
      set { _npc_id = value; }
    }
    private int _unit_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"unit_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unit_id
    {
      get { return _unit_id; }
      set { _unit_id = value; }
    }
    private GameFrameworkMessage.Position _cur_pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cur_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public GameFrameworkMessage.Position cur_pos
    {
      get { return _cur_pos; }
      set { _cur_pos = value; }
    }
    private float _face_direction;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"face_direction", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float face_direction
    {
      get { return _face_direction; }
      set { _face_direction = value; }
    }
    private int _link_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"link_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int link_id
    {
      get { return _link_id; }
      set { _link_id = value; }
    }
    private int _camp_id = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"camp_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int camp_id
    {
      get { return _camp_id; }
      set { _camp_id = value; }
    }
    private int _owner_id = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int owner_id
    {
      get { return _owner_id; }
      set { _owner_id = value; }
    }
    private int _leader_id = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"leader_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int leader_id
    {
      get { return _leader_id; }
      set { _leader_id = value; }
    }
    private uint _key = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint key
    {
      get { return _key; }
      set { _key = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_DebugSpaceInfo")]
  public partial class Msg_RC_DebugSpaceInfo : global::ProtoBuf.IExtensible
  {
    public Msg_RC_DebugSpaceInfo() {}
    
    private readonly global::System.Collections.Generic.List<GameFrameworkMessage.Msg_RC_DebugSpaceInfo.DebugSpaceInfo> _space_infos = new global::System.Collections.Generic.List<GameFrameworkMessage.Msg_RC_DebugSpaceInfo.DebugSpaceInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"space_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameFrameworkMessage.Msg_RC_DebugSpaceInfo.DebugSpaceInfo> space_infos
    {
      get { return _space_infos; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DebugSpaceInfo")]
  public partial class DebugSpaceInfo : global::ProtoBuf.IExtensible
  {
    public DebugSpaceInfo() {}
    
    private int _obj_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"obj_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int obj_id
    {
      get { return _obj_id; }
      set { _obj_id = value; }
    }
    private bool _is_player;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"is_player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_player
    {
      get { return _is_player; }
      set { _is_player = value; }
    }
    private float _pos_x;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private float _pos_z;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pos_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_z
    {
      get { return _pos_z; }
      set { _pos_z = value; }
    }
    private float _face_dir;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"face_dir", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float face_dir
    {
      get { return _face_dir; }
      set { _face_dir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_DestroyNpc")]
  public partial class Msg_RC_DestroyNpc : global::ProtoBuf.IExtensible
  {
    public Msg_RC_DestroyNpc() {}
    
    private int _npc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"npc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int npc_id
    {
      get { return _npc_id; }
      set { _npc_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_HighlightPrompt")]
  public partial class Msg_RC_HighlightPrompt : global::ProtoBuf.IExtensible
  {
    public Msg_RC_HighlightPrompt() {}
    
    private string _dict_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dict_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string dict_id
    {
      get { return _dict_id; }
      set { _dict_id = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _argument = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"argument", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> argument
    {
      get { return _argument; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_ImpactDamage")]
  public partial class Msg_RC_ImpactDamage : global::ProtoBuf.IExtensible
  {
    public Msg_RC_ImpactDamage() {}
    
    private int _role_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"role_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int role_id
    {
      get { return _role_id; }
      set { _role_id = value; }
    }
    private int _attacker_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"attacker_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attacker_id
    {
      get { return _attacker_id; }
      set { _attacker_id = value; }
    }
    private int _damage_status;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"damage_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage_status
    {
      get { return _damage_status; }
      set { _damage_status = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _energy = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int energy
    {
      get { return _energy; }
      set { _energy = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Flag")]
    public enum Flag
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"IS_KILLER", Value=1)]
      IS_KILLER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IS_CRITICAL", Value=2)]
      IS_CRITICAL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IS_ORDINARY", Value=4)]
      IS_ORDINARY = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_LockFrame")]
  public partial class Msg_RC_LockFrame : global::ProtoBuf.IExtensible
  {
    public Msg_RC_LockFrame() {}
    
    private float _scale;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_NpcDead")]
  public partial class Msg_RC_NpcDead : global::ProtoBuf.IExtensible
  {
    public Msg_RC_NpcDead() {}
    
    private int _npc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"npc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int npc_id
    {
      get { return _npc_id; }
      set { _npc_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_NpcFace")]
  public partial class Msg_RC_NpcFace : global::ProtoBuf.IExtensible
  {
    public Msg_RC_NpcFace() {}
    
    private int _npc_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"npc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int npc_id
    {
      get { return _npc_id; }
      set { _npc_id = value; }
    }
    private int _face_direction;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"face_direction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int face_direction
    {
      get { return _face_direction; }
      set { _face_direction = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_NpcMove")]
  public partial class Msg_RC_NpcMove : global::ProtoBuf.IExtensible
  {
    public Msg_RC_NpcMove() {}
    
    private int _npc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"npc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int npc_id
    {
      get { return _npc_id; }
      set { _npc_id = value; }
    }
    private int _velocity = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"velocity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int velocity
    {
      get { return _velocity; }
      set { _velocity = value; }
    }
    private ulong _cur_pos = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cur_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong cur_pos
    {
      get { return _cur_pos; }
      set { _cur_pos = value; }
    }
    private ulong _target_pos = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"target_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong target_pos
    {
      get { return _target_pos; }
      set { _target_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_NpcSkill")]
  public partial class Msg_RC_NpcSkill : global::ProtoBuf.IExtensible
  {
    public Msg_RC_NpcSkill() {}
    
    private int _npc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"npc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int npc_id
    {
      get { return _npc_id; }
      set { _npc_id = value; }
    }
    private int _skill_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private ulong _stand_pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"stand_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong stand_pos
    {
      get { return _stand_pos; }
      set { _stand_pos = value; }
    }
    private int _face_direction;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"face_direction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int face_direction
    {
      get { return _face_direction; }
      set { _face_direction = value; }
    }
    private int _target_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_NpcStopSkill")]
  public partial class Msg_RC_NpcStopSkill : global::ProtoBuf.IExtensible
  {
    public Msg_RC_NpcStopSkill() {}
    
    private int _npc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"npc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int npc_id
    {
      get { return _npc_id; }
      set { _npc_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_PlayAnimation")]
  public partial class Msg_RC_PlayAnimation : global::ProtoBuf.IExtensible
  {
    public Msg_RC_PlayAnimation() {}
    
    private int _obj_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"obj_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int obj_id
    {
      get { return _obj_id; }
      set { _obj_id = value; }
    }
    private string _anim_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"anim_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string anim_name
    {
      get { return _anim_name; }
      set { _anim_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_PublishEvent")]
  public partial class Msg_RC_PublishEvent : global::ProtoBuf.IExtensible
  {
    public Msg_RC_PublishEvent() {}
    
    private bool _is_logic_event;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"is_logic_event", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_logic_event
    {
      get { return _is_logic_event; }
      set { _is_logic_event = value; }
    }
    private string _ev_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ev_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ev_name
    {
      get { return _ev_name; }
      set { _ev_name = value; }
    }
    private string _group;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string group
    {
      get { return _group; }
      set { _group = value; }
    }
    private readonly global::System.Collections.Generic.List<GameFrameworkMessage.Msg_RC_PublishEvent.EventArg> _args = new global::System.Collections.Generic.List<GameFrameworkMessage.Msg_RC_PublishEvent.EventArg>();
    [global::ProtoBuf.ProtoMember(4, Name=@"args", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameFrameworkMessage.Msg_RC_PublishEvent.EventArg> args
    {
      get { return _args; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EventArg")]
  public partial class EventArg : global::ProtoBuf.IExtensible
  {
    public EventArg() {}
    
    private GameFrameworkMessage.ArgType _val_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"val_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.ArgType val_type
    {
      get { return _val_type; }
      set { _val_type = value; }
    }
    private string _str_val;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"str_val", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string str_val
    {
      get { return _str_val; }
      set { _str_val = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_RemoveImpact")]
  public partial class Msg_RC_RemoveImpact : global::ProtoBuf.IExtensible
  {
    public Msg_RC_RemoveImpact() {}
    
    private int _obj_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"obj_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int obj_id
    {
      get { return _obj_id; }
      set { _obj_id = value; }
    }
    private int _impact_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"impact_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int impact_id
    {
      get { return _impact_id; }
      set { _impact_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_RemoveSkill")]
  public partial class Msg_RC_RemoveSkill : global::ProtoBuf.IExtensible
  {
    public Msg_RC_RemoveSkill() {}
    
    private int _obj_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"obj_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int obj_id
    {
      get { return _obj_id; }
      set { _obj_id = value; }
    }
    private int _skill_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_SendGfxMessage")]
  public partial class Msg_RC_SendGfxMessage : global::ProtoBuf.IExtensible
  {
    public Msg_RC_SendGfxMessage() {}
    
    private bool _is_with_tag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"is_with_tag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_with_tag
    {
      get { return _is_with_tag; }
      set { _is_with_tag = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private readonly global::System.Collections.Generic.List<GameFrameworkMessage.Msg_RC_SendGfxMessage.EventArg> _args = new global::System.Collections.Generic.List<GameFrameworkMessage.Msg_RC_SendGfxMessage.EventArg>();
    [global::ProtoBuf.ProtoMember(4, Name=@"args", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameFrameworkMessage.Msg_RC_SendGfxMessage.EventArg> args
    {
      get { return _args; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EventArg")]
  public partial class EventArg : global::ProtoBuf.IExtensible
  {
    public EventArg() {}
    
    private GameFrameworkMessage.ArgType _val_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"val_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.ArgType val_type
    {
      get { return _val_type; }
      set { _val_type = value; }
    }
    private string _str_val;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"str_val", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string str_val
    {
      get { return _str_val; }
      set { _str_val = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_ShakeHands_Ret")]
  public partial class Msg_RC_ShakeHands_Ret : global::ProtoBuf.IExtensible
  {
    public Msg_RC_ShakeHands_Ret() {}
    
    private GameFrameworkMessage.Msg_RC_ShakeHands_Ret.RetType _auth_result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"auth_result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameFrameworkMessage.Msg_RC_ShakeHands_Ret.RetType auth_result
    {
      get { return _auth_result; }
      set { _auth_result = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RetType")]
    public enum RetType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR", Value=1)]
      ERROR = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_ShowDlg")]
  public partial class Msg_RC_ShowDlg : global::ProtoBuf.IExtensible
  {
    public Msg_RC_ShowDlg() {}
    
    private int _dialog_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dialog_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dialog_id
    {
      get { return _dialog_id; }
      set { _dialog_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_SyncNpcOwnerId")]
  public partial class Msg_RC_SyncNpcOwnerId : global::ProtoBuf.IExtensible
  {
    public Msg_RC_SyncNpcOwnerId() {}
    
    private int _npc_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"npc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int npc_id
    {
      get { return _npc_id; }
      set { _npc_id = value; }
    }
    private int _owner_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int owner_id
    {
      get { return _owner_id; }
      set { _owner_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_RC_SyncProperty")]
  public partial class Msg_RC_SyncProperty : global::ProtoBuf.IExtensible
  {
    public Msg_RC_SyncProperty() {}
    
    private int _role_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"role_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int role_id
    {
      get { return _role_id; }
      set { _role_id = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _np;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"np", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int np
    {
      get { return _np; }
      set { _np = value; }
    }
    private int _shield;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"shield", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shield
    {
      get { return _shield; }
      set { _shield = value; }
    }
    private int _state;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Position")]
  public partial class Position : global::ProtoBuf.IExtensible
  {
    public Position() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ArgType")]
    public enum ArgType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NULL", Value=0)]
      NULL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INT", Value=1)]
      INT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FLOAT", Value=2)]
      FLOAT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STRING", Value=3)]
      STRING = 3
    }
  
}