//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: table.proto
namespace TableConfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillList")]
  public partial class SkillList : global::ProtoBuf.IExtensible
  {
    public SkillList() {}
    
    private readonly global::System.Collections.Generic.List<TableConfig.Skill> _items = new global::System.Collections.Generic.List<TableConfig.Skill>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TableConfig.Skill> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Skill")]
  public partial class Skill : global::ProtoBuf.IExtensible
  {
    public Skill() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _desc;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _icon;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private float _distance;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private float _cooldown;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"cooldown", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float cooldown
    {
      get { return _cooldown; }
      set { _cooldown = value; }
    }
    private float _BaseCooldown;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"BaseCooldown", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float BaseCooldown
    {
      get { return _BaseCooldown; }
      set { _BaseCooldown = value; }
    }
    private float _duration;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"duration", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float duration
    {
      get { return _duration; }
      set { _duration = value; }
    }
    private float _interval;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"interval", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float interval
    {
      get { return _interval; }
      set { _interval = value; }
    }
    private int _damage;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private int _mpRecover;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"mpRecover", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mpRecover
    {
      get { return _mpRecover; }
      set { _mpRecover = value; }
    }
    private int _hpRecover;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"hpRecover", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hpRecover
    {
      get { return _hpRecover; }
      set { _hpRecover = value; }
    }
    private int _addAttack;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"addAttack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int addAttack
    {
      get { return _addAttack; }
      set { _addAttack = value; }
    }
    private int _addShield;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"addShield", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int addShield
    {
      get { return _addShield; }
      set { _addShield = value; }
    }
    private float _addSpeed;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"addSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float addSpeed
    {
      get { return _addSpeed; }
      set { _addSpeed = value; }
    }
    private int _canmove;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"canmove", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int canmove
    {
      get { return _canmove; }
      set { _canmove = value; }
    }
    private string _leadAnim;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"leadAnim", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string leadAnim
    {
      get { return _leadAnim; }
      set { _leadAnim = value; }
    }
    private int _leadAnimTime;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"leadAnimTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int leadAnimTime
    {
      get { return _leadAnimTime; }
      set { _leadAnimTime = value; }
    }
    private string _leadEffect;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"leadEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string leadEffect
    {
      get { return _leadEffect; }
      set { _leadEffect = value; }
    }
    private string _leadEffectBone;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"leadEffectBone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string leadEffectBone
    {
      get { return _leadEffectBone; }
      set { _leadEffectBone = value; }
    }
    private int _leadEffectStartTime;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"leadEffectStartTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int leadEffectStartTime
    {
      get { return _leadEffectStartTime; }
      set { _leadEffectStartTime = value; }
    }
    private int _leadEffectDeleteTime;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"leadEffectDeleteTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int leadEffectDeleteTime
    {
      get { return _leadEffectDeleteTime; }
      set { _leadEffectDeleteTime = value; }
    }
    private string _castAnim;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"castAnim", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string castAnim
    {
      get { return _castAnim; }
      set { _castAnim = value; }
    }
    private int _castAnimTime;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"castAnimTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int castAnimTime
    {
      get { return _castAnimTime; }
      set { _castAnimTime = value; }
    }
    private string _selfEffect;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"selfEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string selfEffect
    {
      get { return _selfEffect; }
      set { _selfEffect = value; }
    }
    private string _selfEffectBone;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"selfEffectBone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string selfEffectBone
    {
      get { return _selfEffectBone; }
      set { _selfEffectBone = value; }
    }
    private int _selfEffectStartTime;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"selfEffectStartTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int selfEffectStartTime
    {
      get { return _selfEffectStartTime; }
      set { _selfEffectStartTime = value; }
    }
    private int _selfEffectDeleteTime;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"selfEffectDeleteTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int selfEffectDeleteTime
    {
      get { return _selfEffectDeleteTime; }
      set { _selfEffectDeleteTime = value; }
    }
    private string _targetEffect;
    [global::ProtoBuf.ProtoMember(29, IsRequired = true, Name=@"targetEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string targetEffect
    {
      get { return _targetEffect; }
      set { _targetEffect = value; }
    }
    private string _targetEffectBone;
    [global::ProtoBuf.ProtoMember(30, IsRequired = true, Name=@"targetEffectBone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string targetEffectBone
    {
      get { return _targetEffectBone; }
      set { _targetEffectBone = value; }
    }
    private int _targetEffectStartTime;
    [global::ProtoBuf.ProtoMember(31, IsRequired = true, Name=@"targetEffectStartTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetEffectStartTime
    {
      get { return _targetEffectStartTime; }
      set { _targetEffectStartTime = value; }
    }
    private int _targetEffectDeleteTime;
    [global::ProtoBuf.ProtoMember(32, IsRequired = true, Name=@"targetEffectDeleteTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetEffectDeleteTime
    {
      get { return _targetEffectDeleteTime; }
      set { _targetEffectDeleteTime = value; }
    }
    private string _emitEffect;
    [global::ProtoBuf.ProtoMember(33, IsRequired = true, Name=@"emitEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string emitEffect
    {
      get { return _emitEffect; }
      set { _emitEffect = value; }
    }
    private string _emitEffectBone;
    [global::ProtoBuf.ProtoMember(34, IsRequired = true, Name=@"emitEffectBone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string emitEffectBone
    {
      get { return _emitEffectBone; }
      set { _emitEffectBone = value; }
    }
    private int _emitEffectStartTime;
    [global::ProtoBuf.ProtoMember(35, IsRequired = true, Name=@"emitEffectStartTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int emitEffectStartTime
    {
      get { return _emitEffectStartTime; }
      set { _emitEffectStartTime = value; }
    }
    private int _emitSpeed;
    [global::ProtoBuf.ProtoMember(36, IsRequired = true, Name=@"emitSpeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int emitSpeed
    {
      get { return _emitSpeed; }
      set { _emitSpeed = value; }
    }
    private string _hitAnim;
    [global::ProtoBuf.ProtoMember(37, IsRequired = true, Name=@"hitAnim", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string hitAnim
    {
      get { return _hitAnim; }
      set { _hitAnim = value; }
    }
    private int _hitAnimTime;
    [global::ProtoBuf.ProtoMember(38, IsRequired = true, Name=@"hitAnimTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hitAnimTime
    {
      get { return _hitAnimTime; }
      set { _hitAnimTime = value; }
    }
    private string _hitEffect;
    [global::ProtoBuf.ProtoMember(39, IsRequired = true, Name=@"hitEffect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string hitEffect
    {
      get { return _hitEffect; }
      set { _hitEffect = value; }
    }
    private string _hitEffectBone;
    [global::ProtoBuf.ProtoMember(40, IsRequired = true, Name=@"hitEffectBone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string hitEffectBone
    {
      get { return _hitEffectBone; }
      set { _hitEffectBone = value; }
    }
    private int _hitEffectStartTime;
    [global::ProtoBuf.ProtoMember(41, IsRequired = true, Name=@"hitEffectStartTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hitEffectStartTime
    {
      get { return _hitEffectStartTime; }
      set { _hitEffectStartTime = value; }
    }
    private int _hitEffectDeleteTime;
    [global::ProtoBuf.ProtoMember(42, IsRequired = true, Name=@"hitEffectDeleteTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hitEffectDeleteTime
    {
      get { return _hitEffectDeleteTime; }
      set { _hitEffectDeleteTime = value; }
    }
    private int _impactToSelf;
    [global::ProtoBuf.ProtoMember(43, IsRequired = true, Name=@"impactToSelf", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int impactToSelf
    {
      get { return _impactToSelf; }
      set { _impactToSelf = value; }
    }
    private int _impactToTarget;
    [global::ProtoBuf.ProtoMember(44, IsRequired = true, Name=@"impactToTarget", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int impactToTarget
    {
      get { return _impactToTarget; }
      set { _impactToTarget = value; }
    }
    private int _interruptPriority;
    [global::ProtoBuf.ProtoMember(45, IsRequired = true, Name=@"interruptPriority", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int interruptPriority
    {
      get { return _interruptPriority; }
      set { _interruptPriority = value; }
    }
    private bool _isInterrupt;
    [global::ProtoBuf.ProtoMember(46, IsRequired = true, Name=@"isInterrupt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isInterrupt
    {
      get { return _isInterrupt; }
      set { _isInterrupt = value; }
    }
    private int _targetType;
    [global::ProtoBuf.ProtoMember(47, IsRequired = true, Name=@"targetType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetType
    {
      get { return _targetType; }
      set { _targetType = value; }
    }
    private int _aoeType;
    [global::ProtoBuf.ProtoMember(48, IsRequired = true, Name=@"aoeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int aoeType
    {
      get { return _aoeType; }
      set { _aoeType = value; }
    }
    private float _aoeSize;
    [global::ProtoBuf.ProtoMember(49, IsRequired = true, Name=@"aoeSize", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float aoeSize
    {
      get { return _aoeSize; }
      set { _aoeSize = value; }
    }
    private float _aoeAngleOrLength;
    [global::ProtoBuf.ProtoMember(50, IsRequired = true, Name=@"aoeAngleOrLength", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float aoeAngleOrLength
    {
      get { return _aoeAngleOrLength; }
      set { _aoeAngleOrLength = value; }
    }
    private int _maxAoeTargetCount;
    [global::ProtoBuf.ProtoMember(51, IsRequired = true, Name=@"maxAoeTargetCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxAoeTargetCount
    {
      get { return _maxAoeTargetCount; }
      set { _maxAoeTargetCount = value; }
    }
    private int _dslSkillId;
    [global::ProtoBuf.ProtoMember(52, IsRequired = true, Name=@"dslSkillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dslSkillId
    {
      get { return _dslSkillId; }
      set { _dslSkillId = value; }
    }
    private string _dslFile;
    [global::ProtoBuf.ProtoMember(53, IsRequired = true, Name=@"dslFile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string dslFile
    {
      get { return _dslFile; }
      set { _dslFile = value; }
    }
    private string _sound;
    [global::ProtoBuf.ProtoMember(54, IsRequired = true, Name=@"sound", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sound
    {
      get { return _sound; }
      set { _sound = value; }
    }
    private int _soundDelay;
    [global::ProtoBuf.ProtoMember(55, IsRequired = true, Name=@"soundDelay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int soundDelay
    {
      get { return _soundDelay; }
      set { _soundDelay = value; }
    }
    private float _skilltimescale;
    [global::ProtoBuf.ProtoMember(56, IsRequired = true, Name=@"skilltimescale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float skilltimescale
    {
      get { return _skilltimescale; }
      set { _skilltimescale = value; }
    }
    private int _skilltimescalestarttime;
    [global::ProtoBuf.ProtoMember(57, IsRequired = true, Name=@"skilltimescalestarttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skilltimescalestarttime
    {
      get { return _skilltimescalestarttime; }
      set { _skilltimescalestarttime = value; }
    }
    private int _skilltimescaleendtime;
    [global::ProtoBuf.ProtoMember(58, IsRequired = true, Name=@"skilltimescaleendtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skilltimescaleendtime
    {
      get { return _skilltimescaleendtime; }
      set { _skilltimescaleendtime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}