skill(117)
{  
  section(1000)
  {
    animation("Attack");
    adjustsectionduration("anim",100);
    selfeffect(selfEffect,1000,"eyes",0)
    {
      transform(vector3(0,1,0));
    };
    sendstorymessage(50,"ez_skill_r");
  };
};