// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Data.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace GameFrameworkData
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GeneralRecordData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<string> PrimaryKeys { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<string> ForeignKeys { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int DataVersion { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public byte[] Data
        {
            get => __pbn__Data;
            set => __pbn__Data = value;
        }
        public bool ShouldSerializeData() => __pbn__Data != null;
        public void ResetData() => __pbn__Data = null;
        private byte[] __pbn__Data;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableAccount : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string AccountId { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string Password { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public bool IsBanned { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public ulong UserGuid { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public string Nickname { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableActivationCode : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string ActivationCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public bool IsActivated { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string AccountId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableFriendInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong Guid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong UserGuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public ulong FriendGuid { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public string FriendNickname { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public long QQ { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public long weixin { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public bool IsBlack { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableGlobalData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string Key { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int IntValue { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public float FloatValue { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public string StrValue { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableGuid : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string GuidType { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong GuidValue { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableItemInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong ItemGuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong UserGuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int ItemId { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int ItemNum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableMailInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong Guid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string Sender { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public long Receiver { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public string SendDate { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public string ExpiryDate { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public string Title { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public string Text { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public int Money { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public int Gold { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public string ItemIds { get; set; }

        [global::ProtoBuf.ProtoMember(11, IsRequired = true)]
        public string ItemNumbers { get; set; }

        [global::ProtoBuf.ProtoMember(12, IsRequired = true)]
        public int LevelDemand { get; set; }

        [global::ProtoBuf.ProtoMember(13, IsRequired = true)]
        public bool IsRead { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableMailStateInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong MailGuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong UserGuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public bool IsRead { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public bool IsReceived { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public bool IsDeleted { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public string ExpiryDate { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableMemberInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong MemberGuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong UserGuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int HeroId { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableNicknameInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string Nickname { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong UserGuid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableUserInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong Guid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string AccountId { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string Nickname { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int HeroId { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public string CreateTime { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public string LastLogoutTime { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public int ExpPoints { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public int SceneId { get; set; }

        [global::ProtoBuf.ProtoMember(10, IsRequired = true)]
        public float PositionX { get; set; }

        [global::ProtoBuf.ProtoMember(11, IsRequired = true)]
        public float PositionZ { get; set; }

        [global::ProtoBuf.ProtoMember(12, IsRequired = true)]
        public float FaceDir { get; set; }

        [global::ProtoBuf.ProtoMember(13, IsRequired = true)]
        public int Money { get; set; }

        [global::ProtoBuf.ProtoMember(14, IsRequired = true)]
        public int Gold { get; set; }

        [global::ProtoBuf.ProtoMember(15, IsRequired = true)]
        public string IntDatas { get; set; }

        [global::ProtoBuf.ProtoMember(16, IsRequired = true)]
        public string FloatDatas { get; set; }

        [global::ProtoBuf.ProtoMember(17, IsRequired = true)]
        public string StringDatas { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
